{% set name = "vaex-hdf5" %}
{% set version = "0.5.2" %}
{% set sha256 = "b47ce4f0a214a29e71fc1229285fbb4c4c8685ca970fccc39e0abff933405f61" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - vaex-core >=0.1
    - h5py >=2.9
    - s3fs

test:
  imports:
    - vaex.hdf5

about:
  home: https://www.github.com/maartenbreddels/vaex
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: hdf5 file support for vaex

extra:
  recipe-maintainers:
    - maartenbreddels
