{% set name = "vaex-hdf5" %}
{% set version = "0.5.5" %}
{% set sha256 = "8d32237f72fabb8c066e90a337f739ce6417b6d52a7b597c8ea03855044f3d06" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - vaex-core >=1.0.0,<2
    - h5py >=2.9
    - s3fs <0.3

test:
  imports:
    - vaex.hdf5

about:
  home: https://www.github.com/maartenbreddels/vaex
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: hdf5 file support for vaex

extra:
  recipe-maintainers:
    - maartenbreddels
