travis:
  secure:
    BINSTAR_TOKEN: NjBAw90Yq5MO6gZvpiMO6s1Bvmdp65WRAVNX6IVR2Vyei/DX3JMlfPFeyoyXJidJABGEMX+1UIXCKfKliHzf5hBDHzMDyrw8gODkelhWcWQoRP9jDs3s4WXhPfz8K9qbRRoQ7NzEQXJUESKQZvCFduZeUndPH/Z3KljtsQzpZLaoe0tQNoqI1spLQC62Bm/JbkYj+7B25AgnBFuYF80q6JO011qSpdJeXQWkW8+SdBL8zPUKJKgBBJGt4DJWOFD1N5cz6yQo0ssfbmL6wBZ6qh1d9k/eKlWqT4aIWcgZL7oXslgMGsQMzPIxz7kfdFumbQ/I5lMGcWtuusOnnS2rqL24mU5jLfJ+CEeNC76BgGB4++vUU+UG8vV9Ee9RP3V9meKJcSaxk4Uo+ypz/XAEzF85jI5s93UkursKLDHASVS4WhAPY955SRX7yMpM0ZQ02+X2bWd/PsPDHMWE4StodEj4fDF6/GtOeo26cQPykQsSAksAEvnjQyOrtci9mr3j+L3GanZ9lTsKGPiw71h5LhoXSWI/Z4Cqp5thmyRggYgClgVtu2exqYljgvrbrGt9CKmjxTJg6uAypo3y/htyroOQ/k2pyG7FMw3kNhGdzpwLSRuBPLnlmQFxQlo0uuMxqzMWBgzUc6y5CXYG0r+D5IDl5p4TrXQDn5zOEqkmY6U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
