travis:
  secure:
    BINSTAR_TOKEN: IQDG/gjAqMNaLEt/8xQQqTcSMCd8d1awHdzTpSfw2yy9gPBZI2siiFnSfJObXqxRAOUV3AIlESiEokHs47JvW65QiYzBZfhI34/HL2dNJgvOEFKnCmcc/SjdzLNwrq9nGPfKFw3vYjHAScAtRcfKC8FYyxkdAY4pkH+/As3vuKwpc0534ZSGzDuciutRhOjujKgf3oMNJBznNjXJYamLxWNH6bdk4wOMh3af2IKcswOGC6eDCzy8J+bRdEjIIxdD9MDyDx2dinkvP0zDve5eO9WwrQfnhWKkJ+LE8BO7Wv+9diMkz+wxZiNk+6iqflMpw4lQIfwe9fM4IYsd9fToj6PvKjyZuHl2oSZu+LPiki4VcKOwCAlI3SxSpqt3xjUfyRd0YM2c4luMCwdAueW3EFYQ7wFkeRxtIO49GYvrl3QcWebOiLzfzkWxcrkRFsYzNKQ1GbGwX0QUqlq5bBAUnB1uFNdlGqOKgsjKUqOWagfLMGVgg/eSw9gnrpyX76ewzPxNtdiFMfvIrIWkPxBbY6XPJE+enHQpRSCo4iEEC2OTfmOpBx6poFtph77tgsJXFFGn7L8AFEgk2mtBaIcokoepNTepGogtv3iOn5Wrc/2DtOGi1OKHK/IieWStL7bIezpgz+rWPrMkxV4OYidSB0zxpoJl7zr2iVl/q2rezTc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
